server:
  port: 8080

spring:
  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    showSql: true
#    properties.hibernate.hbm2ddl.auto: create-drop
    database: mysql
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pickmeup?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 340709

  messages:
    basename: i18n/exception
    encoding: UTF-8

  jwt:
    secret: govlepel@$&

